theme: jekyll-text-theme

text_skin: default #eg: default | dark | forest | ocean | chocolate | orange

## Base settings ##
# url:  #the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: /
title: szakallas.eu
description: > #this means to ignore newlines until "nav_lists:"
  Dávid Szakállas's homepage

paths:
  base: /
  home: /
  archive: /all/
  rss:  /feed.xml

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      license: false
      aside:
        toc: true
      show_edit_on_github: false
      pageview: false

## GitHub repository (if the site is hosted by GitHub) ##
repository: dszakallas/profile
repository_tree: master

## Language & timezone ##
lang: en #the language of your site, eg: en(English), zh(简体中文), zh-Hans(简体中文), zh-Hant(繁體中文)
timezone: Europe/Budapest #see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values

## Author & social ##
author:
  name: Szakállas Dávid
  email:  #your Email address e.g. someone@site.com
  # facebook:  #your Facebook username
  twitter: szdavid92
  github: dszakallas
  # googleplus:  #your Google+ username
  # weibo:  #your Weibo username
  # douban:  #your Douban username
  linkedin:  dszakallas

license: CC-BY-4.0

## TOC
toc:
  # selectors: 'h1,h2,h3'

# mathjax: true
# mathjax_autoNumber: true
# mermaid: true
# chart: true

## Paginate ##
paginate: 7
paginate_path: /blog/page:num/

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: text # text | html

## Sources ##
# sources: bootcss #eg: bootcss | unpkg

## Build ##
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

exclude:
  - .travis.yml
  - Dockerfile
  - docker-compose.yml
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor
  - /tmp

## Plugins ##
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"
