theme: jekyll-text-theme

text_skin: dark #eg: default | dark | forest | ocean | chocolate | orange
highlight_theme: tomorrow-night
## Base settings ##
# url:  #the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: /
title: szakallas.eu
description: > #this means to ignore newlines until "nav_lists:"
  Dávid Szakállas's homepage

paths:
  root: /
  home: /
  archive: /all/
  rss: /feed.xml

# license: CC-BY-NC-4.0

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      pageview: true

## GitHub repository (if the site is hosted by GitHub) ##
repository: dszakallas/profile
repository_tree: master

## Language & timezone ##
lang: en #the language of your site, eg: en(English), zh(简体中文), zh-Hans(简体中文), zh-Hant(繁體中文)
timezone: Europe/Budapest #see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values

## Author & social ##
author:
  name: Szakállas Dávid
  email:  #your Email address e.g. someone@site.com
  # facebook:  #your Facebook username
  twitter: szdavid92
  github: dszakallas
  # googleplus:  #your Google+ username
  # weibo:  #your Weibo username
  # douban:  #your Douban username
  linkedin:  dszakallas

## TOC
toc:
  # selectors: 'h1,h2,h3'

# comments:
#   provider: disqus
#   disqus:
#     shortname: kitian616-github-io

# analytics:
#   provider: google
#   google:
#     tracking_id: UA-71907556-1

## Reading quantity (LeanCloud) ##
leancloud:
  # app_id:  #LeanCloud App id
  # app_key:  #LeanCloud App key
  # app_class:  #LeanCloud App class

# mathjax: true
# mathjax_autoNumber: true
# mermaid: true
# chart: true

## Paginate ##
paginate: 7
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: text # text | html

## Sources ##
# sources: bootcss #eg: bootcss | unpkg

## Build ##
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

## Plugins ##
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"
