# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "playwright-1.59.0-alpha-1770338664000" = {
      name = "playwright";
      packageName = "playwright";
      version = "1.59.0-alpha-1770338664000";
      src = fetchurl {
        url = "https://registry.npmjs.org/playwright/-/playwright-1.59.0-alpha-1770338664000.tgz";
        sha512 = "YKR5ko/eQFtcvlZPTJN3BmVFRrIxuzKw8sqZgP9XY+JvQEDlAsGDNsBd7/TxWLZYzCC8HHETB7cW6Ru2DEkTWA==";
      };
    };
    "playwright-core-1.59.0-alpha-1770338664000" = {
      name = "playwright-core";
      packageName = "playwright-core";
      version = "1.59.0-alpha-1770338664000";
      src = fetchurl {
        url = "https://registry.npmjs.org/playwright-core/-/playwright-core-1.59.0-alpha-1770338664000.tgz";
        sha512 = "Qlaafyf5T1GN/ynNJVVdJyD26HjzqvgRC62jNdfaFoMkTvqSlV4of9O6BV7c1x5ZJpplKXHecAPWKSWNdea7Dw==";
      };
    };
  };
in
{
  "@playwright/mcp" = nodeEnv.buildNodePackage {
    name = "_at_playwright_slash_mcp";
    packageName = "@playwright/mcp";
    version = "0.0.64";
    src = fetchurl {
      url = "https://registry.npmjs.org/@playwright/mcp/-/mcp-0.0.64.tgz";
      sha512 = "vH/DYCpBedfU/aBs9+jYyZLRD71ubHQyN/VEcIL1F60skJAJYxlccpvGB7oxN8K0AECl7zcvpZm0lbMSp2MX1A==";
    };
    dependencies = [
      sources."playwright-1.59.0-alpha-1770338664000"
      sources."playwright-core-1.59.0-alpha-1770338664000"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Playwright Tools for MCP";
      homepage = "https://playwright.dev";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
