name: Jekyll site CI - Production

on:  # yamllint disable-line rule:truthy
  push:
    branches: [ "**" ]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: devenv
      - run: nix profile install nixpkgs#devenv
      - run: devenv test

  publish-prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: devenv
      - run: nix profile install nixpkgs#devenv
      - run: devenv build outputs.production > out
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::588757185393:role/ProfileGHAMainBranch
      - run: |
          upload --distribution "${{ secrets.DISTRIBUTION_PROD }}" \
            "$(cat out)" "${{ vars.BUCKET_PROD }}"
        shell: devenv shell bash -- -e {0}


  publish-staging:
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: devenv
      - run: nix profile install nixpkgs#devenv
      - run: devenv build outputs.staging > out
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::588757185393:role/ProfileGHAStagingBranch
      - run: |
          upload --distribution "${{ secrets.DISTRIBUTION_STG }}" \
            "$(cat out)"  "${{ vars.BUCKET_STG }}"
        shell: devenv shell bash -- -e {0}
