name: CI

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - "**"

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - run: nix profile install nixpkgs#devenv
      - run: devenv test --dont-override-dotfile
      - name: Apply autofixes
        if: |
          failure() &&
          contains(github.event.pull_request.labels.*.name, 'autofix')
        shell: devenv shell bash -- -e {0}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore: apply autofixes"
            FIX_COMMIT_SHA=$(git rev-parse HEAD)
            git checkout ${{ github.head_ref }}
            git cherry-pick ${FIX_COMMIT_SHA}
            git push origin ${{ github.head_ref }}
          fi

  publish-prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - run: nix profile install nixpkgs#devenv
      - run: devenv build outputs.production > out
      - uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::588757185393:role/ProfileGHAMainBranch
      - run: |
          upload --distribution "${{ secrets.DISTRIBUTION_PROD }}" \
            "$(cat out)" "${{ vars.BUCKET_PROD }}"
        shell: devenv shell bash -- -e {0}


  publish-staging:
    if: github.event_name == 'push' && github.ref == 'refs/heads/staging'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - run: nix profile install nixpkgs#devenv
      - run: devenv build outputs.staging > out
      - uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::588757185393:role/ProfileGHAStagingBranch
      - run: |
          upload --distribution "${{ secrets.DISTRIBUTION_STG }}" \
            "$(cat out)"  "${{ vars.BUCKET_STG }}"
        shell: devenv shell bash -- -e {0}
