name: Jekyll site CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container: earthly/earthly:v0.6.2
    env:
      DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
      BUCKET_NAME: "szakallas.eu"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      EARTHLY_CI: 1
    steps:
    - uses: actions/checkout@v2
    - run: docker volume create earthly-cache
    - name: Cache 
      id: cache-primes
      uses: actions/cache@v2
      with:
        path: /var/lib/docker/volumes/earthly-cache
        key: earthly-build
    - name: Build the site
      run: earthly +site
    - run: ls -la /var/lib/docker
