name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  env:
    DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
    BUCKET_NAME: "szakallas.eu"
    AWS_REGION: "us-east-1"
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    EARTHLY_CI: 1
  build:
    runs-on: earthly/earthly:v0.6.2
    steps:
    - uses: actions/checkout@v2
    - name: Build the site
      run: earthly +site
    - name: Upload site to S3
      run: earthly --secret AWS_ACCESS_KEY_ID --secret AWS_SECRET_ACCESS_KEY +upload-to-s3 --BUCKET_NAME="szakallas.eu" --AWS_REGION=${AWS_REGION}
    - name: Invalidate CloudFront cache
      run: earthly --secret DISTRIBUTION --secret AWS_ACCESS_KEY_ID --secret AWS_SECRET_ACCESS_KEY +invalidate-cf --AWS_REGION=${AWS_REGION}
