name: Jekyll site CI - Staging

on:
  push:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: earthly/earthly:v0.6.2
    env:
      BUCKET_NAME: "szakallas.stg.eu"
      AWS_REGION: "us-east-2"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      EARTHLY_CI: 1
    steps:
    - uses: actions/checkout@v2
    - name: Build the site
      run: earthly +site --JEKYLL_BUILD_ARGS="--future"
    - name: Upload site to S3
      run: earthly --secret AWS_ACCESS_KEY_ID --secret AWS_SECRET_ACCESS_KEY +upload-to-s3 --JEKYLL_BUILD_ARGS="--future" --BUCKET_NAME="szakallas.stg.eu"
